### ISSUE TITLE
parseAsync?

### ISSUE THREAD

**Issue by sonewman** [alexmarqs/zod-config#8]
great package btw, i would love to use it, but the schema i have needs to use an async transform.

This unfortuately isn't possible because when the config is loaded is is parsed with `safeParse` as opposed to `safeParseAsync`.

I don't know if this is something you would want to consider in some shape or form?

**Comment by alexmarqs** [comment]
Hey @sonewman, thanks! Your point makes total sense, actually initially I was not considering schemas involving async refine/transformations. Internally I believe I can make use of the safeParseAsync by default instead of safeParse. I will do the change and add some unit tests to cover this as well.

**Comment by alexmarqs** [comment]
Changes committed! I can make a release only with this if you want ;) ref commit: https://github.com/alexmarqs/zod-config/commit/aaed26c257bd5d6095199c05cfc4111ff768c866

**Comment by sonewman** [comment]
awesome, this is perfect. thanks for the speedy response

**Comment by alexmarqs** [comment]
Released 0.0.5! 

If this package is helping you I appreciate your star in the repo, thank you 👍
